### ISSUE TITLE
v2 gives "File not found: '/matt-usurp/validate-semver/v2.0.0/build/action.mjs'"

### ISSUE THREAD

**Issue by MaikVermeulen** [matt-usurp/validate-semver#5]
First of all, thank you for making this Action! We've been using it in our pipeline for a while now 😄 

With the upgrade to `v2`, we're getting this error:

![image](https://github.com/matt-usurp/validate-semver/assets/27008793/f4d1c79b-4f68-43e7-9238-d0cff511887a)

```
Error: File not found: '/home/dev/github-runners/runner2/_work/_actions/matt-usurp/validate-semver/v2.0.0/build/action.mjs'
```

**Comment by matt-usurp** [comment]
I will take a look, this is weird. My guess is this will be a fairly simple fix.

Edit: Also thanks! I thought for the longest time this thing wasn't in use, you do not get any metrics as an actions owner.

**Comment by matt-usurp** [comment]
I believe I have fixed this, pushed new tag `v2.0.1` and changes are updated on the `v2` branch

**Comment by MaikVermeulen** [comment]
> I believe I have fixed this, pushed new tag `v2.0.1` and changes are updated on the `v2` branch

Thank you @matt-usurp for the stellar response time!

The file is now being found, but it seems there is another error:
```
file:///_actions/matt-usurp/validate-semver/v2.0.1/build/action.mjs:12
  throw Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "os" is not supported
    at file:///home/dev/github-runners/runner1/_work/_actions/matt-usurp/validate-semver/v2.0.1/build/action.mjs:12:9
    at node_modules/@actions/core/lib/command.js (file:///home/dev/github-runners/runner1/_work/_actions/matt-usurp/validate-semver/v2.0.1/build/action.mjs:108:27)
    at __require2 (file:///home/dev/github-runners/runner1/_work/_actions/matt-usurp/validate-semver/v2.0.1/build/action.mjs:18:[5](https://github.com/Quattio/cic-yocto-builder/actions/runs/8611010570/job/23597450361#step:8:6)0)
    at node_modules/@actions/core/lib/core.js (file:///home/dev/github-runners/runner1/_work/_actions/matt-usurp/validate-semver/v2.0.1/build/action.mjs:2040:21)
    at __require2 (file:///home/dev/github-runners/runner1/_work/_actions/matt-usurp/validate-semver/v2.0.1/build/action.mjs:18:50)
    at file:///home/dev/github-runners/runner1/_work/_actions/matt-usurp/validate-semver/v2.0.1/build/action.mjs:2[6](https://github.com/Quattio/cic-yocto-builder/actions/runs/8611010570/job/23597450361#step:8:7)81:2[7](https://github.com/Quattio/cic-yocto-builder/actions/runs/8611010570/job/23597450361#step:8:8)
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.[8](https://github.com/Quattio/cic-yocto-builder/actions/runs/8611010570/job/23597450361#step:8:9).1
```

**Comment by matt-usurp** [comment]
Okay, I might need to revert the `esm` upgrade and keep `cjs` on `node@20`
I will give it a go in an hour or so, sorry about this

**Comment by matt-usurp** [comment]
Right, I hope this is fixed, I have run tests and it seems to work for me now.
Sorry about this, seems to be a problem with `@actions/core` not compiling for the newer syntaxes

**Comment by MaikVermeulen** [comment]
Seems to be good now, thanks a ton @matt-usurp! We appreciate the quick resolution 💪
